DROP POLICY IF EXISTS results_tenant_isolation ON results;
ALTER TABLE results NO FORCE ROW LEVEL SECURITY;
ALTER TABLE results DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS runs_tenant_isolation ON runs;
ALTER TABLE runs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE runs DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS prompts_tenant_isolation ON prompts;
ALTER TABLE prompts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE prompts DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS datasets_tenant_isolation ON datasets;
ALTER TABLE datasets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE datasets DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS api_keys_tenant_isolation ON api_keys;
ALTER TABLE api_keys NO FORCE ROW LEVEL SECURITY;
ALTER TABLE api_keys DISABLE ROW LEVEL SECURITY;
